// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ZxG6iIeAu5whUQb4SCH1gX1sBnadkHA',
    appId: '1:346987314553:web:1c14c764dfecf6bbb9c3a8',
    messagingSenderId: '346987314553',
    projectId: 'gps-ercaller',
    authDomain: 'gps-ercaller.firebaseapp.com',
    databaseURL: 'https://gps-ercaller-default-rtdb.firebaseio.com',
    storageBucket: 'gps-ercaller.appspot.com',
    measurementId: 'G-HKK5ZCSGMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLL1PiGr7ALtwKpuNqMStkEakoPw1h5E',
    appId: '1:346987314553:android:084b86b6082f2d1cb9c3a8',
    messagingSenderId: '346987314553',
    projectId: 'gps-ercaller',
    databaseURL: 'https://gps-ercaller-default-rtdb.firebaseio.com',
    storageBucket: 'gps-ercaller.appspot.com',
  );

}